# Copyright 2021 Facundo Ciccioli
# See LICENSE file for licensing details.

options:
  url:
    type: string
    default: "nagios.example.com"
    description: "URL to use for web virtual host"
  trusted_ssl_cert:
    type: string
    default: ''
    description: |
        Name and location of the remotely trusty ssl cert.  Basename of this file
        will be used as the basename of the chain file rooted at
        /etc/ssl/certs.
  trusted_ssl_certlocation:
    type: string
    default: ''
    description: |
        Name and location of the remotely trusty ssl cert.  Basename of this file
        will be used as the basename of the chain file rooted at
        /etc/ssl/certs.
  log-path:
    default: "/var/log/thruk/thruk.log"
    type: string
    description: >
      The default log path.
  debug-log:
    default: false
    type: boolean
    description: >
      Enables debug logging for thruk.
  debug-log-path:
    default: "/var/log/thruk/debug.log"
    type: string
    description: >
      The default log path for debugging (if enabled).
  screen-log:
    default: false
    type: boolean
    description: >
      Enables debug logging to stderr for thruk - in the default case, this ends
      up in the apache error logs.
