# Copyright 2021 Facundo Ciccioli
# See LICENSE file for licensing details.

options:
  url:
    type: string
    default: "nagios.example.com"
    description: "URL to use for web virtual host"
  log-path:
    default: "/var/log/thruk/thruk.log"
    type: string
    description: >
      The default log path.
  debug-log:
    default: false
    type: boolean
    description: >
      Enables debug logging for thruk.
  debug-log-path:
    default: "/var/log/thruk/debug.log"
    type: string
    description: >
      The default log path for debugging (if enabled).
  screen-log:
    default: false
    type: boolean
    description: >
      Enables debug logging to stderr for thruk - in the default case, this ends
      up in the apache error logs.
